kernel:
  image: linuxkit/kernel:4.14.52
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:e24105ebb339e1a2e578fde7ec8bccf844a633d5
  - linuxkit/runc:1dc6559fd0a9a332c740312637af0c3fbe6bafa3
  - linuxkit/containerd:ed0589d53e29890b0e504f594a0e4af7326b6484
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: rngd1
    image: linuxkit/rngd:v0.6
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.6
services:
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: webwormhole
    image: webwormhole:latest
    capabilities:
      - CAP_NET_BIND_SERVICE
    command: ["/bin/ww", "server", "-hosts", "webwormhole.io,wrmhl.link,tip.webwormhole.io,oursink.com,"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
  - name: sshd
    image: linuxkit/sshd:v0.6
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
  - path: etc/linuxkit-config
    metadata: yaml
